// llmService.ts
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || "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";
const MODEL_NAME = process.env.OPENROUTER_MODEL || "google/gemini-2.0-flash-001";

interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export async function generateResponse(
  systemPrompt: string,
  conversationHistory: Message[],
  options?: any
): Promise<string> {
  try {
    const messages: Message[] = [
      { role: 'system', content: systemPrompt },
      ...conversationHistory,
    ];

    console.log(`[OpenRouter] Generating response using model: ${MODEL_NAME}`);
    
    const requestBody: any = {
      model: MODEL_NAME,
      messages: messages,
      temperature: options?.temperature ?? 0.7,
      max_tokens: options?.max_tokens ?? 1024,
    };

    if (options?.format === "json") {
        requestBody.response_format = { type: "json_object" };
    }

    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${OPENROUTER_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`OpenRouter HTTP error! status: ${response.status}, message: ${errText}`);
    }

    const result: any = await response.json();
    let content = result?.choices?.[0]?.message?.content || "";
    
    // Strip out <think> tags often generated by reasoning models
    if (content) {
        content = content.replace(/<think>[\s\S]*?<\/think>/g, '').trim();
    }

    return content;
  } catch (error: any) {
    console.error('[OpenRouter] API Error:', error.message || error);
    throw new Error("Cannot reach OpenRouter or model failed.");
  }
}
